### ISSUE TITLE
Display GitHub home instead of doc URI

### ISSUE THREAD

**Issue by dmcassel** [grtjn/ml-github-search#28]
Search result titles look like `/marklogic/roxy.json`, which makes me think I'm looking at a file in a repo. Showing `/marklogic/roxy` or `https://github.com/marklogic/roxy` would make it clear that this is a repo result.

**Comment by grtjn** [comment]
Yeah, thinking of `marklogic/roxy`. Should be a trivial change..

**Comment by grtjn** [comment]
Fixed
